### ISSUE TITLE
xdt99 introduce version strings

### ISSUE THREAD

**Issue by FilipVanVooren** [endlos99/xdt99#34]
As discussed on Atariage; we've seen that as xdt99 advances, over the years assembly source code cannot longer be successfully assembled due to subtle changes or errors. Due to this I'd like to lock my assembly source to specific xas99 version.

Proposal: introduce XDT99 version strings that can be queried and acted upon during assembly.

**Comment by endlos99** [comment]
Thanks for your report!  Are you referring to the error message that Asmusr posted recently?  If so, I've just fixed that.

Do you have any other examples where old programs won't assemble any more?

**Comment by MirrorPusher** [comment]
Was referring to that yes. Having said that my use case would be to have access to the xas99 version string so that I could include it into the output binary that I assemble.

Why? If I get bug reports (and that can happen years later, it would be great to find out what source code version of my program I assembled (have that in place), and the assembler version used to assemble that particular piece of code.
With that in place I pretty much have everything I need to reproduce the bug

**Comment by endlos99** [comment]
Good idea!  And I think I'll include it in the error output as well, in case someone asks about some error messages.

**Comment by endlos99** [comment]
The latest version (released for some while now) has a built-in .VERS macro that is issues the current version as text bytes.  The version also prefixes stderr.
