### ISSUE TITLE
Problem with 2+ spaces in BYTE directive data

### ISSUE THREAD

**Issue by petersobolev** [endlos99/xdt99#6]
...
          BYTE 100, 64, 04, >0E     ; ok
...
          BYTE 100, 64,  04, >0E     ; syntax error 
...

(two spaces after "64," on second line)

**Comment by endlos99** [comment]
Thanks for submitting a bug report!

The behavior you observe is intended and due to the fact that xas99 needs (or wants) to be backwards compatible to existing assembly sources.

In the original TI Assembler, a space would separate the argument from the comment field.  Thus, you often see code like

`LABEL LI R0,SIZE*2 DOUBLE BUFFER SIZE`

If you allow whitespace inside arguments, like xas99, you may run into ambiguity:

`LABEL LI R1, SIZE * 2 * DOUBLE BUFFER SIZE`

Is the actual size `SIZE*2` or `SIZE*2*DOUBLE`?

So xas99 makes a compromise and allows single spaces in arguments only, and two or more spaces (or tab) introduce the comment field.  This makes source code much more legible, but minimizes code incompatibility.

Having said all that, though, I think I can improve upon the current behavior, so I leave this ticket open and will work on this as soon as I find some time.

**Comment by petersobolev** [comment]
Thanks for an answers!

It might be useful to implement two modes in xas: 
1. "compatibility" mode - to compile existing/old sources 
2. "enhanced" mode - with syntax rules as in majority of assemblers, incompatible with aged TI features.

I think there are many people who just trying to code something for TMS9900 first time (like me). And some traditional TI assembler features looks really strange after 6502/6809/x86 assemblers, for example.

**Comment by endlos99** [comment]
The mode you're currently using is already the "enhanced" mode.  Try adding the "-s" switch to enjoy the original TI Assembler experience ...

But yes, I'll add more lenient whitespaces in arguments, thanks for bringing that up.

**Comment by endlos99** [comment]
Well, that took some time, but with new release 3.2.0 I introduced a relaxed syntax where you can put arbitrary spaces within an instruction.  The trade-off is that all comments (except comments starting with *) need to be prefixed with `;`.

This mode is enabled with option `-r`, which can also be added to `XAS99_CONFIG` is you want to enable it automatically for all programs you're editing.

For details, see the manual or this [abbreviated version](https://github.com/endlos99/xdt99/blob/master/doc/MANUAL.diff).
